version: "3.3"

services:
  clickhouse1:
    image: yandex/clickhouse-server:21.3.3.14
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
#    volumes:
#      - ./config/local.xml:/etc/clickhouse-server/config.d/local.xml
  
  tarantool1:
    image: tarantool/tarantool:2.7.2 
    # x.x.0 = alpha, x.x.1 = beta, x.x.2+ = stable, latest not always stable
#    volumes:
#      - ./tarantool-data:/usr/local/share/tarantool
    ports:
      - "3301:3301"

#  typesense1:
#    image: typesense/typesense:0.21.0
#    command: ./typesense-server --data-dir=/data --api-key=123
##    volumes:
##      - ./typesense-data:/data
#    ports:
#      - "8108:8108"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
