version: "3.3"

services:

  clickhouse1:
    image: yandex/clickhouse-server:latest # 21.8.11.4
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
#    volumes:
#      - ./config/local.xml:/etc/clickhouse-server/config.d/local.xml
  
  tarantool1:
    image: tarantool/tarantool:latest # 2.8.2 
    # x.x.0 = alpha, x.x.1 = beta, x.x.2+ = stable, latest not always stable
    environment:
      TARANTOOL_USER_NAME: "myusername" 
      TARANTOOL_USER_PASSWORD: "mysecretpassword"
      #TT_READAHEAD: '1632000' # 10x   
      #TT_VINYL_MEMORY: '2684354560' # 20x
      #TT_VINYL_CACHE: '2684354560' # 20x
      #TT_NET_MSG_MAX: '76800' # 100x
      #TT_MEMTX_MEMORY: '268435456' # 1x
      #TT_VINYL_PAGE_SIZE: '8192' # 1x
    volumes:
      - ./backup/tarantool-data:/var/lib/tarantool
      - ./docker/opt_tarantool_app.lua:/opt/tarantool/app.lua
    #entrypoint: /entrypoint.sh /opt/tarantool/app.lua
    ports:
      - "3301:3301"

#  typesense1:
#    image: typesense/typesense:0.21.0
#    command: ./typesense-server --data-dir=/data --api-key=123
##    volumes:
##      - ./typesense-data:/data
#    ports:
#      - "8108:8108"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
