name: Test Example Pipeline

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x] #, 1.16.x 
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: |
          cd W2/example && go test ./...
